### ISSUE TITLE
data.BlockHash can be nil, and this line blows up

### ISSUE THREAD

**Issue by shruggr** [bitcoin-sv/arc#116]
https://github.com/bitcoin-sv/arc/blob/dfbfb10e289f1179c32bfed711165e55170d738c/metamorph/server.go#L498

```
        txn := &metamorph_api.Transaction{
		Txid:         data.Hash.String(),
		AnnouncedAt:  announcedAt,
		StoredAt:     storedAt,
		MinedAt:      minedAt,
		Status:       data.Status,
		BlockHeight:  data.BlockHeight,
		RejectReason: data.RejectReason,
		RawTx:        data.RawTx,
	}
	if data.BlockHash != nil {
		txn.BlockHash = data.BlockHash.String()
	}
        return txn, nil
```

**Comment by shruggr** [comment]
Stack Trace of error: 
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xf49998]

goroutine 608172 [running]:
github.com/bitcoin-sv/arc/metamorph.(*Server).GetTransaction(0x14977a8?, {0x14977a8?, 0xc00d451e00?}, 0x1d0afa0?)
        /home/gorillapool/arc/metamorph/server.go:497 +0x98
github.com/bitcoin-sv/arc/metamorph/metamorph_api._MetaMorphAPI_GetTransaction_Handler.func1({0x14977a8, 0xc00d451e00}, {0x10e2020?, 0xc00d600b00})
        /home/gorillapool/arc/metamorph/metamorph_api/metamorph_api_grpc.pb.go:205 +0x72
github.com/grpc-ecosystem/grpc-opentracing/go/otgrpc.OpenTracingServerInterceptor.func1({0x14977a8, 0xc00d451d10}, {0x10e2020, 0xc00d600b00}, 0xc00f5d3000, 0xc00d617818)
        /home/gorillapool/go/pkg/mod/github.com/grpc-ecosystem/grpc-opentracing@v0.0.0-20180507213350-8e809c8a8645/go/otgrpc/server.go:57 +0x3d0
google.golang.org/grpc.getChainUnaryHandler.func1({0x14977a8, 0xc00d451d10}, {0x10e2020, 0xc00d600b00})
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1156 +0xb2
github.com/grpc-ecosystem/go-grpc-prometheus.init.(*ServerMetrics).UnaryServerInterceptor.func3({0x14977a8, 0xc00d451d10}, {0x10e2020, 0xc00d600b00}, 0xc00f5d3000?, 0xc00d600b40)
        /home/gorillapool/go/pkg/mod/github.com/grpc-ecosystem/go-grpc-prometheus@v1.2.0/server_metrics.go:107 +0x7d
google.golang.org/grpc.NewServer.chainUnaryServerInterceptors.chainUnaryInterceptors.func1({0x14977a8, 0xc00d451d10}, {0x10e2020, 0xc00d600b00}, 0xc00054ba50?, 0x1061a80?)
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1147 +0x85
github.com/bitcoin-sv/arc/metamorph/metamorph_api._MetaMorphAPI_GetTransaction_Handler({0x1151e40?, 0xc000515c80}, {0x14977a8, 0xc00d451d10}, 0xc00d6623f0, 0xc000244880)
        /home/gorillapool/arc/metamorph/metamorph_api/metamorph_api_grpc.pb.go:207 +0x135
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0003663c0, {0x149e080, 0xc00dfb11e0}, 0xc00bbf30e0, 0xc00071c5a0, 0x1cc64a8, 0x0)
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1337 +0xde7
google.golang.org/grpc.(*Server).handleStream(0xc0003663c0, {0x149e080, 0xc00dfb11e0}, 0xc00bbf30e0, 0x0)
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:1714 +0x9e7
google.golang.org/grpc.(*Server).serveStreams.func1.1()
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:959 +0x8d
created by google.golang.org/grpc.(*Server).serveStreams.func1 in goroutine 601285
        /home/gorillapool/go/pkg/mod/google.golang.org/grpc@v1.55.0/server.go:957 +0x165
```

**Comment by shruggr** [comment]
Resolved in https://github.com/bitcoin-sv/arc/pull/117

**Comment by boecklim** [comment]
PR https://github.com/bitcoin-sv/arc/pull/117 is approved and merged
Thank you for the contribution
